services:
  - type: web
    name: django-hospital
    env: python
    rootDir: .
    buildCommand: |
      pip install -r requirements.txt
      bash render-build.sh
    startCommand: gunicorn hospital_system.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: hospital_system.settings

