services:
  - type: web
    name: colegio-schoolcomms
    env: python
    buildCommand: |
      pip install -r requirements.txt
      bash render-build.sh
    startCommand: gunicorn schoolcomms.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
